model_path: /home/cl/Machiko_v1/Machiko/sft/machiko_zh_en
model_name: machiko_zh_en_100k
batch_size: 10

zero_shot_template: 
  no_input: "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Response:"
  with_input: "Below is an instruction that describes a task, paired with an input that provides further context. Write a response that appropriately completes the request.\n\n### Instruction:\n{instruction}\n\n### Input:\n{input}\n\n### Response:"

few_shot_template:
  instance_template: "{input} {output}"
  split_by: ","
  question_prompt: " {input}"

generate_config:
  do_sample: True
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  num_beams: 1
  max_new_tokens: 600
